### PR TITLE
(SDI-2025) Fixes #14 and #15. Proper namespace setting and const correctness

### LINKED ISSUE #14: Metric::set_ns() method appends namespace instead of setting it
Hi,

I noticed that Metric::set_ns() method (https://github.com/intelsdi-x/snap-plugin-lib-cpp/blob/101d785d302882ee3b3c346aff39aeaecb20c5f8/src/snap/metric.cc#L71) doesn't work correctly. Based on its name I was under impression that it should set Metric's namespace to a new value passed as an argument. However current implementation appends argument to already existing namespace.

I think rpc_metric_ptr->clear_namespace_(); method should be called from Metric::set_ns() before for loop. (https://github.com/intelsdi-x/snap-plugin-lib-cpp/blob/101d785d302882ee3b3c346aff39aeaecb20c5f8/src/snap/metric.cc#L72)

By the way, it appears that memo_ns variable is not used in this method.

Regards,
Przemek

### PR DESCRIPTION
**Pull request by marcin-krolik**
Fixes #14 and #15 

- `Metric:set_ns()` is now properly set
- const correctness on getters
- changes interface for `collect_metrics`, `process_metrics` and `publish_metrics` to reference to vector

@intelsdi-x/snap-maintainers  @intelsdi-x/plugin-maintainers

### CODE REVIEW

**Comment by marcintao** [comment]
LGTM

File: src/snap/metric.cc [hunk 1]
```diff
@@ -96,15 +103,14 @@ const std::vector<Metric::NamespaceElement>& Metric::ns() {
...
 
-std::vector<int> Metric::dynamic_ns_elements() {
-  const std::vector<Metric::NamespaceElement>& namesp = ns();
+std::vector<int> Metric::dynamic_ns_elements() const {
   std::vector<int> idxs;
-  int i = 0;
-  for (Metric::NamespaceElement nse : namesp) {
-    if (!nse.name.empty()) {
-      idxs.push_back(i);
+  RepeatedPtrField<rpc::NamespaceElement> rpc_ns = rpc_metric_ptr->namespace_();
```
Comment (pszczerx) [inline src/snap/metric.cc]: Why are you no longer using Metric::ns() function?

Comment (marcin-krolik) [inline src/snap/metric.cc]: It was changed due to `const` requirement on `dynamic_ns_element`, but since `memo_ns` is now `mutable` I guess it's good idea to come back to call `ns()` method which does lazy init on `memo_ns`.

**Comment by marcin-krolik** [comment]
@pszczerx Const correctness added on `tags()` and `timestamp()`
